
CONFLUENT:
  URL: pkc-ymrq7.us-east-2.aws.confluent.cloud:9092
  USERNAME: HA7JZAZD7FGDKCHQ
  PASSWORD: HSgDlNuBrF838tJ5ECXdUhJDmqjsq+KhrBfmR8uJgGKkR/3I1Wapu23apns97kg8
  SCHEMA_REG_URL: https://psrc-yg906.us-east-2.aws.confluent.cloud
  SCHEMA_REG_USER: 2Z7V6Q4XCFHCNUXN:Yhd1d1sQSGFWWBwlNyXiljDEY7harmijW1VJB2hbZB2mwsDlodxxGWC0l7NRyfwv

KAFKA_GROUP_ID: EVENT_GROUP
KAFKA_TOPIC_NAME: EVENT_GROUP